version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpg_app
    environment:
    #   XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=172.17.0.1"
    # extra_hosts:
    #   - "docker.host.internal:host-gateway" 
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - rpg_network

  db:
    image: mysql:5.7
    container_name: rpg_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_rpg_321
      MYSQL_DATABASE: rpg
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql  
    networks:
      - rpg_network

  web:
    image: nginx:latest
    container_name: rpg_web
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - rpg_network


networks:
  rpg_network:
    driver: bridge

volumes:
  dbdata:  
